language: python

stages:
  - test

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y -qq sqlite3 libsqlite3-dev
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt

matrix:
  include:
    - python: pypy3.5-7.0
      env: TEST=pypy3
    - python: 3.5
      env: TEST=py3.5
    - python: 3.6
      env: TEST=py3.6
    - python: 3.7
      env: TEST=py3.7

script:
  - if [ "${TEST}" == 'pypy3' ]; then
      OPTIONS = '-p no:faulthandler'
    else
      OPTIONS = ''
    fi;
  - coverage run -m pytest $OPTIONS tests -vv

after_success:
  - coverage report -m

